### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Luxfero00000** [CompassSecurity/TokenPhisher#2]

**Comment by Luxfero00000** [comment]
please I will appreciate a reply , I want to know if this is a bug on my side that I have to fix or the it isn't just possible for the code to pull request from Microsoft's Api

**Comment by sploutchy** [comment]
Hi @Luxfero00000 ,
Hopefully you found a solution to your problem.
Otherwise, don't hesitate to come back to use with some more details.
Cheers
