### ISSUE TITLE
fixed 

### ISSUE THREAD

**Issue by Luxfero00000** [CompassSecurity/TokenPhisher#3]
fixed

**Comment by Luxfero00000** [comment]
I am still waiting for your response. Thanks

**Comment by sploutchy** [comment]
Dear @Luxfero00000,
The person responsible for this project is on holiday. I plan on looking into your issue as soon as I have some time, this may take several weeks. 
Best,

**Comment by Luxfero00000** [comment]
I will be expecting a response from you soon . Thanks
